# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0.xci
# IP: The module: 'vfifo_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0.xci
# IP: The module: 'vfifo_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
