# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0.xci
# IP: The module: 'vfifo_rst_mig_7series_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0.xci
# IP: The module: 'vfifo_rst_mig_7series_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/gpif_vfifo/gpif_vfifo.srcs/sources_1/bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vfifo_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
