
# On board LED
set_property PACKAGE_PIN AA1 [get_ports led_0]
set_property IOSTANDARD SSTL135 [get_ports led_0]
set_property PACKAGE_PIN AA5 [get_ports led_1]
set_property IOSTANDARD SSTL135 [get_ports led_1]
set_property PACKAGE_PIN AA6 [get_ports led_2]
set_property IOSTANDARD SSTL135 [get_ports led_2]

# On board button
set_property PACKAGE_PIN AA14 [get_ports button_0]
set_property IOSTANDARD LVCMOS33 [get_ports button_0]

# On board configuration flash
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]


# On board physical clocks, 100MHz(10ns) USER_CLK D17 & 100MHz SYS_CLK K4
set_property PACKAGE_PIN D17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10 -name clk -waveform {0.000 5.000} [get_ports clk]


# GBA Cartridge Edge Connector
set_property PACKAGE_PIN T21  [get_ports {gba_phi     }]
set_property PACKAGE_PIN U21  [get_ports {gba_wr      }]
set_property PACKAGE_PIN W22  [get_ports {gba_rd      }]
set_property PACKAGE_PIN W21  [get_ports {gba_cs1     }]
set_property PACKAGE_PIN Y22  [get_ports {gba_adl[0]  }]
set_property PACKAGE_PIN Y21  [get_ports {gba_adl[1]  }]
set_property PACKAGE_PIN AB22 [get_ports {gba_adl[2]  }]
set_property PACKAGE_PIN AB21 [get_ports {gba_adl[3]  }]
set_property PACKAGE_PIN AA21 [get_ports {gba_adl[4]  }]
set_property PACKAGE_PIN AA20 [get_ports {gba_adl[5]  }]
set_property PACKAGE_PIN AB20 [get_ports {gba_adl[6]  }]
set_property PACKAGE_PIN AA19 [get_ports {gba_adl[7]  }]
set_property PACKAGE_PIN R17  [get_ports {gba_adl[8]  }]
set_property PACKAGE_PIN P16  [get_ports {gba_adl[9]  }]
set_property PACKAGE_PIN Y19  [get_ports {gba_adl[10] }]
set_property PACKAGE_PIN W17  [get_ports led_wr        ]
set_property PACKAGE_PIN V17  [get_ports led_rd        ]
set_property PACKAGE_PIN U20  [get_ports {gba_adl[11] }]
set_property PACKAGE_PIN V20  [get_ports {gba_adl[12] }]
set_property PACKAGE_PIN P19  [get_ports {gba_adl[13] }]
set_property PACKAGE_PIN R19  [get_ports {gba_adl[14] }]
set_property PACKAGE_PIN T18  [get_ports {gba_adl[15] }]
set_property PACKAGE_PIN R18  [get_ports {gba_adh[0]  }]
set_property PACKAGE_PIN W20  [get_ports {gba_adh[1]  }]
set_property PACKAGE_PIN W19  [get_ports {gba_adh[2]  }]
set_property PACKAGE_PIN V19  [get_ports {gba_adh[3]  }]
set_property PACKAGE_PIN V18  [get_ports {gba_adh[4]  }]
set_property PACKAGE_PIN U18  [get_ports {gba_adh[5]  }]
set_property PACKAGE_PIN U17  [get_ports {gba_adh[6]  }]
set_property PACKAGE_PIN P17  [get_ports {gba_adh[7]  }]
set_property PACKAGE_PIN N17  [get_ports {gba_cs2     }]
set_property PACKAGE_PIN R16  [get_ports {gba_idreq   }]

set_property IOSTANDARD LVCMOS33 [get_ports {gba_phi     }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_wr      }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_rd      }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_cs1     }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[0]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[1]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[2]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[3]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[4]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[5]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[6]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[7]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[8]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[9]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[10] }]
set_property IOSTANDARD LVCMOS33 [get_ports led_wr        ]
set_property IOSTANDARD LVCMOS33 [get_ports led_rd        ]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[11] }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[12] }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[13] }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[14] }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adl[15] }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[0]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[1]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[2]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[3]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[4]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[5]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[6]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_adh[7]  }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_cs2     }]
set_property IOSTANDARD LVCMOS33 [get_ports {gba_idreq   }]


# USB3.1 FX3 GPIF2 Interface
set_property PACKAGE_PIN J19 [get_ports _gpif_pclk]
set_property PACKAGE_PIN H13 [get_ports {faddr[0]}]
set_property PACKAGE_PIN J14 [get_ports {faddr[1]}]
set_property PACKAGE_PIN M20 [get_ports {fdata[0]}]
set_property PACKAGE_PIN N22 [get_ports {fdata[1]}]
set_property PACKAGE_PIN M22 [get_ports {fdata[2]}]
set_property PACKAGE_PIN L19 [get_ports {fdata[3]}]
set_property PACKAGE_PIN L21 [get_ports {fdata[4]}]
set_property PACKAGE_PIN M21 [get_ports {fdata[5]}]
set_property PACKAGE_PIN M18 [get_ports {fdata[6]}]
set_property PACKAGE_PIN N18 [get_ports {fdata[7]}]
set_property PACKAGE_PIN L15 [get_ports {fdata[8]}]
set_property PACKAGE_PIN L16 [get_ports {fdata[9]}]
set_property PACKAGE_PIN M17 [get_ports {fdata[10]}]
set_property PACKAGE_PIN M13 [get_ports {fdata[11]}]
set_property PACKAGE_PIN M15 [get_ports {fdata[12]}]
set_property PACKAGE_PIN L13 [get_ports {fdata[13]}]
set_property PACKAGE_PIN L18 [get_ports {fdata[14]}]
set_property PACKAGE_PIN L20 [get_ports {fdata[15]}]
set_property PACKAGE_PIN H17 [get_ports {fdata[16]}]
set_property PACKAGE_PIN H14 [get_ports {fdata[17]}]
set_property PACKAGE_PIN K21 [get_ports {fdata[18]}]
set_property PACKAGE_PIN H18 [get_ports {fdata[19]}]
set_property PACKAGE_PIN G13 [get_ports {fdata[20]}]
set_property PACKAGE_PIN J21 [get_ports {fdata[21]}]
set_property PACKAGE_PIN G16 [get_ports {fdata[22]}]
set_property PACKAGE_PIN G15 [get_ports {fdata[23]}]
set_property PACKAGE_PIN K18 [get_ports {fdata[24]}]
set_property PACKAGE_PIN G18 [get_ports {fdata[25]}]
set_property PACKAGE_PIN G17 [get_ports {fdata[26]}]
set_property PACKAGE_PIN J22 [get_ports {fdata[27]}]
set_property PACKAGE_PIN K19 [get_ports {fdata[28]}]
set_property PACKAGE_PIN G20 [get_ports {fdata[29]}]
set_property PACKAGE_PIN H22 [get_ports {fdata[30]}]
set_property PACKAGE_PIN H20 [get_ports {fdata[31]}]
set_property PACKAGE_PIN K22 [get_ports flaga]
set_property PACKAGE_PIN K14 [get_ports flagb]
set_property PACKAGE_PIN J17 [get_ports flagc]
set_property PACKAGE_PIN J16 [get_ports flagd]
set_property PACKAGE_PIN N19 [get_ports pktend]
set_property PACKAGE_PIN L14 [get_ports slcs]
set_property PACKAGE_PIN K17 [get_ports sloe]
set_property PACKAGE_PIN N20 [get_ports slrd]
set_property PACKAGE_PIN K16 [get_ports slwr]

set_property IOSTANDARD LVCMOS18 [get_ports _gpif_pclk]
set_property IOSTANDARD LVCMOS18 [get_ports {faddr[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {faddr[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports flaga]
set_property IOSTANDARD LVCMOS18 [get_ports flagb]
set_property IOSTANDARD LVCMOS18 [get_ports flagc]
set_property IOSTANDARD LVCMOS18 [get_ports flagd]
set_property IOSTANDARD LVCMOS18 [get_ports pktend]
set_property IOSTANDARD LVCMOS18 [get_ports slcs]
set_property IOSTANDARD LVCMOS18 [get_ports sloe]
set_property IOSTANDARD LVCMOS18 [get_ports slrd]
set_property IOSTANDARD LVCMOS18 [get_ports slwr]
