# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/microblaze_ddr_100t/microblaze_ddr_100t.srcs/sources_1/bd/bd_top/ip/bd_top_dlmb_v10_0/bd_top_dlmb_v10_0.xci
# IP: The module: 'bd_top_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/microblaze_ddr_100t/microblaze_ddr_100t.gen/sources_1/bd/bd_top/ip/bd_top_dlmb_v10_0/bd_top_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/microblaze_ddr_100t/microblaze_ddr_100t.srcs/sources_1/bd/bd_top/ip/bd_top_dlmb_v10_0/bd_top_dlmb_v10_0.xci
# IP: The module: 'bd_top_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/microblaze_ddr_100t/microblaze_ddr_100t.gen/sources_1/bd/bd_top/ip/bd_top_dlmb_v10_0/bd_top_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
