# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/vfifo/vfifo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo || ORIG_REF_NAME==vfifo} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_auto_us_0/vfifo_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_auto_us_0 || ORIG_REF_NAME==vfifo_auto_us_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axi_mem_intercon_0/vfifo_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axi_mem_intercon_0 || ORIG_REF_NAME==vfifo_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axi_vfifo_ctrl_0_0/vfifo_axi_vfifo_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axi_vfifo_ctrl_0_0 || ORIG_REF_NAME==vfifo_axi_vfifo_ctrl_0_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axis_data_fifo_0_0/vfifo_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axis_data_fifo_0_0 || ORIG_REF_NAME==vfifo_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axis_data_fifo_1_0/vfifo_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axis_data_fifo_1_0 || ORIG_REF_NAME==vfifo_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axis_switch_0_0/vfifo_axis_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axis_switch_0_0 || ORIG_REF_NAME==vfifo_axis_switch_0_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_axis_switch_1_0/vfifo_axis_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_axis_switch_1_0 || ORIG_REF_NAME==vfifo_axis_switch_1_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_mig_7series_0_0/vfifo_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_mig_7series_0_0 || ORIG_REF_NAME==vfifo_mig_7series_0_0} -quiet] -quiet

# IP: bd/vfifo/ip/vfifo_rst_mig_7series_0_100M_0/vfifo_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vfifo_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==vfifo_rst_mig_7series_0_100M_0} -quiet] -quiet

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/gpif_vfifo/gpif_vfifo.gen/sources_1/bd/vfifo/vfifo_ooc.xdc
