# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/bd_top/bd_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top || ORIG_REF_NAME==bd_top} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_dlmb_v10_0/bd_top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_dlmb_v10_0 || ORIG_REF_NAME==bd_top_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_ilmb_v10_0/bd_top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_ilmb_v10_0 || ORIG_REF_NAME==bd_top_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_dlmb_bram_if_cntlr_0/bd_top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_ilmb_bram_if_cntlr_0/bd_top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_lmb_bram_0/bd_top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_lmb_bram_0 || ORIG_REF_NAME==bd_top_lmb_bram_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_clk_wiz_1_0/bd_top_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_1_0 || ORIG_REF_NAME==bd_top_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_rst_clk_wiz_1_100M_0/bd_top_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_top_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_axi_uartlite_0_0/bd_top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_axi_uartlite_0_0 || ORIG_REF_NAME==bd_top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_microblaze_0_axi_periph_0/bd_top_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bd_top_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_mig_7series_0_0/bd_top_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_mig_7series_0_0 || ORIG_REF_NAME==bd_top_mig_7series_0_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_rst_mig_7series_0_100M_0/bd_top_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==bd_top_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_xbar_0/bd_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_xbar_0 || ORIG_REF_NAME==bd_top_xbar_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_mdm_1_riscv_0/bd_top_mdm_1_riscv_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_mdm_1_riscv_0 || ORIG_REF_NAME==bd_top_mdm_1_riscv_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_microblaze_0_riscv_0/bd_top_microblaze_0_riscv_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_microblaze_0_riscv_0 || ORIG_REF_NAME==bd_top_microblaze_0_riscv_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_auto_us_1/bd_top_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_auto_us_1 || ORIG_REF_NAME==bd_top_auto_us_1} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_auto_ds_0/bd_top_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_auto_ds_0 || ORIG_REF_NAME==bd_top_auto_ds_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_auto_pc_0/bd_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_0 || ORIG_REF_NAME==bd_top_auto_pc_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_auto_us_0/bd_top_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_auto_us_0 || ORIG_REF_NAME==bd_top_auto_us_0} -quiet] -quiet

# IP: bd/bd_top/ip/bd_top_auto_cc_0/bd_top_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_top_auto_cc_0 || ORIG_REF_NAME==bd_top_auto_cc_0} -quiet] -quiet

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA/100T/microblaze_ddr_100t/microblaze_ddr_100t.gen/sources_1/bd/bd_top/bd_top_ooc.xdc
