# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.srcs/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo.xci
# IP: The module: 'hs_rx_pkt_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.gen/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'hs_rx_pkt_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.gen/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hs_rx_pkt_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.srcs/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo.xci
# IP: The module: 'hs_rx_pkt_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.gen/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'hs_rx_pkt_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Projects/Hardware/gba-io/reference/Aritx7/FPGA例程/100T/gpif_vfifo/gpif_vfifo.gen/sources_1/ip/hs_rx_pkt_fifo/hs_rx_pkt_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hs_rx_pkt_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
